pik/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from groupApp import urls as group_url
from UserApp import urls as user_url
from UserApp.admin import admin_site
from UserApp import views
from purchaseApp import urls as purchase_url
from AccountingApp import urls as AccountingAppUrl

admin.autodiscover()

urlpatterns = [
    url(r'^pikadmin/', admin_site.urls),
    url(r'^group/', include(group_url)),
    url(r'^users/', include(user_url)),
    url(r'^purchases/', include(purchase_url)),
    url(r'^$', views.index , name='index'),
    url(r'^accounting/', include(AccountingAppUrl)),
]

purchase/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^payed/$', views.retrieve_all_payed_purchases, name='list'),
    url(r'^unpayed/$', views.retrieve_all_un_payed_purchases, name='list'),
    url(r'^add_form$', views.add_purchase_form, name='list'),
]

themeApp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

groupApp/models.py
from django.db import models

from UserApp.models import CustomizedUser
from django.utils.translation import ugettext_lazy as _


class Group(models.Model):
    title = models.CharField(max_length=255, verbose_name='عنوان گروه')
    admin = models.ForeignKey(CustomizedUser, related_name='group_admin', verbose_name='مدیر گروه ')
    member = models.ManyToManyField(CustomizedUser, blank=True, related_name='group_member', verbose_name='اعضای گروه')
    creation_datetime = models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد گروه')

    def __str__(self):
        return self.title

    def set_admin(self, user_id):
        self.admin = user_id
        self.save()

    class Meta:
        verbose_name = (_("مدیریت گروه‌ها"))
        verbose_name_plural = (_("مدیریت گروه‌ها"))

# class UserGroup(models.Model):
#     group = models.ForeignKey(Group)
#     member = models.ManyToManyField(CustomizedUser)
#     join_datetime = models.DateTimeField(auto_now_add=True)

purchase/models.py
from django.db import models

# Create your models here.


class Purchase (models.Model):
    title = models.CharField(max_length=20)
    price = models.IntegerField(default=0)
    # group_id = models.ForeignKey(Group, on_delete=models.CASCADE)
    group_id = models.IntegerField(null=False)
    status = models.BooleanField(default=False)

themeApp/models.py
from django.db import models

# Create your models here.

themeApp/views.py
from django.shortcuts import render

themeApp/templates/Accounting.html
{% extends 'base.html' %}
{% block title %}امور مالی | سامانه بیک{% endblock %}
{% block balance %}12500{% endblock %}
{% block page_header %}امور مالی{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h2>شارژ حساب</h2>
            <form action="/accounting/charge" method="POST">
                {% if charge_message %}
                    <div id="msg" class="message">
                        {{ charge_message }}
                    </div>
                {% endif %}

                {% if charge_form.errors %}
                    {% for error in charge_form.non_field_errors %}
                        <div class="error_message">
                            {{ error|escape }}
                        </div>
                    {% endfor %}
                {% endif %}

                {% csrf_token %}

                {% for item in charge_form %}
                    {% for error in item.errors %}
                        <div class="error_message">
                            {{ error }}
                        </div>
                    {% endfor %}
                    <div class="float-input">
                        {{ item }}
                        <span><i class="fa fa-user"></i></span>
                    </div>
                {% endfor %}
                <div class="submit-area">
                    <input type="submit" value="شارژ حساب">
                </div>
            </form>
            <ul class="form-notes">
                <li>شارژ حساب به صورت آنلاین و توسط کلیه کارت های عضو شبکه شتاب امکان پذیر میباشد .</li>
                <li>1.5% کارمزد سامانه پیک به مبلغ شما اضافه میگردد .</li>
            </ul>
        </div>

        <div class="col-md-6">
            <h2>درخواست تسویه</h2>
            <form action="/accounting/checkout" method="POST">
                {% if checkout_message %}
                    <div class="message">
                        {{ checkout_message }}
                    </div>
                {% endif %}

                {% if checkout_form.errors %}
                    {% for error in checkout_form.non_field_errors %}
                        <div class="error_message">
                            {{ error|escape }}
                        </div>
                    {% endfor %}
                {% endif %}

                {% csrf_token %}

                {% for item in checkout_form %}
                    {% for error in item.errors %}
                        <div class="error_message">
                            {{ error }}
                        </div>
                    {% endfor %}
                    <div class="float-input">
                        {{ item }}
                        <span><i class="fa fa-user"></i></span>
                    </div>
                {% endfor %}
                <div class="submit-area">
                    <input type="submit" value="درخواست تسویه">
                </div>
            </form>
            <ul class="form-notes">
                <li>واریزها بین 1 تا 3 ساعت پس از درخواست انجام خواهد شد .</li>
                <li>جهت تعیین شماره کارت خود به قسمت بروفایل مراجعه فرمایید .</li>
            </ul>
        </div>
    </div>
    <div class="row">
        <br><br>
        <hr>

        {% if transactions %}
            <h2>لیست تراکنش های شما</h2>
            <div class="tp-groups-table">
                <table class="tftable" border="1">
                    <tr><th>ردیف</th><th>نوع تراکنش</th><th>مبلغ</th><th>تاریخ</th><th>خرید مربوطه</th></tr>
                    {% for trans in transactions %}
                        <tr>
                            <td>{{ trans.pk }}</td>
                            <td>
                                {% if trans.action == 1 %}
                                    شارژ حساب
                                {% elif trans.action == 2 %}
                                    درخواست تسویه
                                {% elif trans.action == 3 %}
                                    واریز به کارت
                                {% elif trans.action == 0 %}
                                    برداخت بیک
                                {% endif %}
                            </td>
                            <td>{{ trans.amount }}</td>
                            <td>{{ trans.date }}</td>
                            <td>
                                {% if trans.portion %}
                                    {{ trans.portion.purchase.title }}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            </div>
        {% endif %}

{% endblock %}

themeApp/templates/AddPurchase.html
{% extends 'base.html' %}
{% block title %}افزودن خرید{% endblock %}
{% block balance %}{% endblock %}
{% block page_header %}افزودن خرید جدید{% endblock %}
{% block content %}
    <form id="add_purchase_form" action="" method="POST">
        {% csrf_token %}
        <div id="msg" class="message">{{ msg }}</div>
        <div class="col-md-6">
            <div class="text-fields">
                <span style="color:red">{{ form.non_field_errors }}</span>
                <div class="float-input">
                    {{ add_form.title }}
                    <span style='color:red;'>{{ add_form.title.errors }}</span>
                    <span><i class="fa fa-cart-plus"></i></span>
                </div>
                <div class="float-input">
                    {{ add_form.price }}
                    <span style='color:red;'>{{ add_form.price.errors }}</span>
                    <span><i class="fa fa-money"></i></span>
                </div>
                <div class="float-input">
                    {{ add_form.group }}
                    <span style='color:red;'>{{ add_form.group.errors }}</span>
                    <span><i class="fa fa-users"></i></span>
                </div>

            </div>
        </div>
        <div class="col-md-6">
            <div class="tp-pic-table">
                <table class="tftable dsn" border="1" id="users_group">
                    <tbody>
                    <tr><th>ردیف</th><th>نام کاربر</th><th>پیک (تومان و یا درصد)</th></tr>
                    </tbody>
                </table>
            </div>
            <div class="submit-area">
                <button type="submit">
                    اضافه کردن خرید
                </button>
            </div>
        </div>
    </form>
{% endblock %}

themeApp/templates/ChangePassword.html
{% extends 'base.html' %}
{% block title %}تغییر گذرواژه | سامانه بیک{% endblock %}
{% block balance %}12500{% endblock %}
{% block page_header %}تغییر گذرواژه{% endblock %}
{% block content %}
    <form action="" method="POST">
        {% if message %}
            <div id="msg" class="message">
                {{ message }}
            </div>
        {% endif %}

        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <div id="msg" class="error_message">
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endif %}

        {% csrf_token %}
        {% for item in form %}
            {% for error in item.errors %}
                <div class="error_message">
                    {{ error }}
                </div>
            {% endfor %}
            <div class="float-input">
                {{ item }}
                <span><i class="fa fa-user"></i></span>
            </div>
        {% endfor %}
        <div class="submit-area">
            <input type="submit" value="بروزرسانی تغییرات">
        </div>
        </div>
    </form>


{% endblock %}

themeApp/templates/CreateGroup.html
{% extends 'base.html' %} {% load static %}
{% block title %}ساخت گروه | سامانه پیک{% endblock %}
{% block balance %}12500{% endblock %}
{% block page_header %}ساخت گروه{% endblock %}
{% block content %}
    <!-- Create Group Main Area -->
    <p>
        برای گروه خود نامی انتخاب کنید ، سپس از طریق فیلد بعدی ، نام کاربری کسانی که مایل هستید در گروه شما عضو باشند وارد نمایید ، با شروع وارد نمودن نام کاربری ، لیست افرادی که آن نام کاربری را دارند برای شما نمایش داده میشود که میتوانید انتخاب نمایید .
        <br>
        برای استفاده از این سامانه ، تمامی اعضا میبایست عضو سایت باشند ، با اضافه کردن اعضا به گروه ، برای آنها دعوتنامه ای از طریق ایمیل ارسال میگردد .
    </p>
    <!-- Create Group Form -->
    <form action="" method="post">
        {% csrf_token %}

        {% if message %}
            <div id="msg" class="message">
                {{ message }}
            </div>
        {% endif %}
        <div class="text-fields">


            <!-- List of Groups-->
            {% if groups_list %}
                {% for group in groups%}
                    {% url 'edit_group' group.id as edit_url%}
                    <table class="table table-bordered" style="text-align: center;">
                        <th style="text-align: center">
                            {% if group.admin == user %}
                                <a href="{{ edit_url }}">
                                    {{ group.title }}
                                </a>
                            {% else %}
                                {{ group.title }}
                            {% endif %}
                        </th>
                        {% for member in group.member.all %}
                            <tr>
                                {% if  group.admin not in group.member.all and forloop.first %}
                                    <td>{{ group.admin }}</td>
                                    <tr>
                                        <td>{{ member }}</td>
                                    </tr>
                                {% else %}
                                    <td>{{ member }}</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </table>
                {% endfor %}
                {#                {% for form in edit_group_form %}#}
                {#                    {% if not forloop.last %}#}
                {#                        {{ form }}#}
                {#                        <span><i class="fa fa-user"></i></span>#}
                {#                        <p>#}
                {#                            {% url 'edit_group' form.id.value as edit_url%}#}
                {#                            <a class="btn btn-info" href="{{ edit_url }}">ویرایش</a>#}
                {#                        </p>#}
                {#                    {% endif %}#}
                {##}
                {#                {% endfor %}#}
            {% endif %}

            <!-- Edit Group Form -->
            {% if edit_group %}
                {{ edit_group_form }}
            {% endif %}

            <!-- Create Group Form -->
            {% if create %}
                {% for item in create_form %}
                    {#                        <div class="float-input ">#}
                    {{ item }}
                    <span><i class="fa fa-user"></i></span>
                    {#                        </div>#}
                {% endfor %}
            {% endif %}


            <div class="submit-area">

                {% if create or edit_group %}
                    <button type="submit" >
                        {% if create %}
                            ساخت گروه
                        {% elif edit_group %}
                            ذخیره
                        {% endif %}
                    </button>
                {% endif %}
            </div>
        </div>
    </form>
    <script type="text/javascript" src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
    {{ create_form.media }}
    {{ edit_group_form.media }}
    <!-- End Create Group Form -->

    <!-- End Create Group Main Area -->
{% endblock %}

themeApp/templates/Groups.html
{% extends 'base.html' %} {% load static %}
{% block title %}ساخت گروه | سامانه پیک{% endblock %}
{% block balance %}12500{% endblock %}
{% block page_header %}ساخت گروه{% endblock %}
{% block content %}

    <!-- Groups Main Area -->
    <div class="col-md-9">
        <h2>گروه هایی که هم اکنون عضو هستید</h2>

        <div class="tp-groups-table">
            <table class="tftable" border="1">
                <tr><th>ردیف</th><th>نام گروه</th><th>سمت</th><th>اعضای گروه</th><th>عملیات</th></tr>
                {% for group in groups %}
                    <tr>
                    {% url 'edit_group' group.id as edit_url%}
                    <td>
                        {{ forloop.counter }}
                    </td>
                    <td>
                        {% if group.admin == user %}
                            <a href="{{ edit_url }}">
                                {{ group.title }}
                            </a>
                        {% else %}
                            {{ group.title }}
                        {% endif %}
                    </td>
                    <td>
                        {{ group.admin }}
                    </td>
                    <td>
                        {% for member in group.member.all %}
                            {% if not forloop.last %}
                                {{ member }} |
                            {% else %}
                                {{ member }}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        <i class="fa fa-sign-out"></i>  |
                        {% if group.admin == user %}
                            <i class="fa fa-cog"></i> |

                        {% endif %}
                        <i class="fa fa-times-circle"></i>
                    </td>

                    {#                            </td><td><i class="fa fa-sign-out"></i><i class="fa fa-cog"></i><i class="fa fa-times-circle"></i></td></tr>#}
                    {#                            <tr><td>2</td><td>همکاران</td><td>عضو</td><td>امیرحسین و امیررضا و محمد</td><td><i class="fa fa-sign-out"></i></td></tr>#}
                    {#                            <tr><td>3</td><td>اکیپ کوهنوردی</td><td>عضو</td><td>امیرحسین و امیررضا و محمد</td><td><i class="fa fa-sign-out"></i></td></tr>#}
                    {#                            <tr><td>4</td><td>منو رضا و حسین</td><td>مدیر</td><td>امیرحسین و امیررضا و محمد</td><td><i class="fa fa-sign-out"></i><i class="fa fa-cog"></i><i class="fa fa-times-circle"></i></td></tr>#}
                {% endfor %}
            </table>
        </div>
        {#        <i class="fa fa-sign-out"></i> لغو عضویت |#}
        {#        <i class="fa fa-cog"></i> مدیریت گروه |#}
        {#        <i class="fa fa-times-circle"></i> حذف گروه#}
    </div>
    <!-- End Groups Main Area -->



    <!-- Import JS Files -->
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
    <!-- Import JS Files -->

{% endblock %}

themeApp/templates/Profile.html
{% extends 'base.html' %}
{% block title %}پروفایل شما | سامانه بیک{% endblock %}
{% block balance %}12500{% endblock %}
{% block page_header %}پروفایل شما{% endblock %}
{% block content %}
    <form action="" method="POST">
        {% if message %}
            <div id="msg" class="message">
                {{ message }}
            </div>
        {% endif %}

        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <div id="msg" class="error_message">
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endif %}

        {% csrf_token %}
        {% for item in form %}
            {% for error in item.errors %}
                <div class="error_message">
                    {{ error }}
                </div>
            {% endfor %}
            <div class="float-input">
                {{ item }}
                <span><i class="fa fa-user"></i></span>
            </div>
        {% endfor %}
        <h4><a href="changepassword">تغییر گذرواژه</a></h4>
        <div class="submit-area">
            <input type="submit" value="بروزرسانی تغییرات">
        </div>
        </div>
    </form>


{% endblock %}

themeApp/templates/PurchaseHistory.html
{% extends 'base.html' %}
{% block title %}تاریخچه خرید{% endblock %}
{% block balance %}{% endblock %}
{% block page_header %}تاریخچه خرید{% endblock %}
{% block content %}
    <!-- Filters -->
    <div class="tp-filters">

        فیلتر خریدها بر اساس گروه :
        <span class="active" id="filter-all" onclick="filterByGroupId(this);">همه</span>
        {% for group in request.user.group_set.all %}
            <span id="filter-{{ group.id }}" onclick="filterByGroupId(this, {{ group.id }});">{{ group.title }}</span>
        {% endfor %}
    </div>
    {% for portion in portions %}
        <div id="purchase-box-01" class="tp-purchase-box" data-group="{{ portion.purchase.group.id }}">
            <div class="col-md-9">
                <h4>{{ purchase.purchase.title }}</h4>
                <div class="tp-purchase-meta">پرداخت شده توسط :<span>{{ portion.user.name }}</span>
                    | در تاریخ :<span>{{ portion.created_at }}</span>
                    | مبلغ کل : <span>{{ portion.purchase.price }} تومان</span>
                </div>
                <div class="tp-pic-table">
                    <table class="tftable" border="1">
                        <tr><th>ردیف</th><th>نام کاربر</th><th>پیک (تومان)</th><th>وضعیت پرداخت</th></tr>
                        {% for user in portion.purchase.group.member.all %}
                            {# starting index 1 #}
                            {% for user_portion in user.portion_set.all %}
                                {% if user_portion.purchase == portion.purchase %}
                                    <tr>
                                        <td>{{ forloop.parentloop.counter }}</td>
                                        <td>{{ user.name }}</td>
                                        <td>{{ user_portion.amount }}</td>
                                        {% if user_portion.status %}
                                            <td class="tp-paied"><i class="fa fa-check-square"></i></td>
                                        {% else %}
                                             <td class="tp-not-paied"><i class="fa fa-times-circle"></i></td>
                                        {% endif %}
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    </table>
                </div>
            </div>
            <div class="col-md-3 tp-pic-box">
                این خرید
                <span>تکمیل</span>
                شده است
                <button name="resend-reciption-mail" id="submit-resend-reciption-mail" onclick="sendReciptionMailMessage();">
                    ارسال مجدد فاکتور به ایمیل شما
                </button>
                کد خرید :
                <span id="purchase-code">#2568A85</span>
            </div>
        </div>
    {% endfor %}
{% endblock %}

themeApp/templates/Purchases.html
{% extends 'base.html' %}
{% block title %}خرید های پرداخت نشده{% endblock %}
{% block balance %}{% endblock %}
{% block page_header %}خرید های پرداخت نشده{% endblock %}
{% block content %}
    <!-- Filters -->
    <div class="tp-filters">

        فیلتر خریدها بر اساس گروه :
        <span class="active" id="filter-all" onclick="filterByGroupId(this);">همه</span>
        {% for group in request.user.group_set.all %}
            <span id="filter-{{ group.id }}" onclick="filterByGroupId(this, {{ group.id }});">{{ group.title }}</span>
        {% endfor %}
    </div>
    {% for portion in portions %}
        <div id="purchase-box-01" class="tp-purchase-box" data-group="{{ portion.purchase.group.id }}">
            <div class="col-md-9">
                <h4>{{ portion.purchase.title }}</h4>
                <div class="tp-purchase-meta">پرداخت شده توسط :<span>{{ portion.user.name }}</span>
                    | در تاریخ :<span>{{ portion.created_at }}</span>
                    | مبلغ کل : <span>{{ portion.purchase.price }} تومان</span>
                </div>
                <div class="tp-pic-table">
                    <table class="tftable" border="1">
                        <tr><th>ردیف</th><th>نام کاربر</th><th>پیک (تومان)</th><th>وضعیت پرداخت</th></tr>
                        {% for user in portion.purchase.group.member.all %}
                            {# starting index 1 #}
                            {% for user_portion in user.portion_set.all %}
                                {% if user_portion.purchase == portion.purchase %}
                                    <tr>
                                        <td>{{ forloop.parentloop.counter }}</td>
                                        <td>{{ user.name }}</td>
                                        <td>{{ user_portion.amount }}</td>
                                        {% if user_portion.status %}
                                            <td class="tp-paied"><i class="fa fa-check-square"></i></td>
                                        {% else %}
                                             <td class="tp-not-paied"><i class="fa fa-times-circle"></i></td>
                                        {% endif %}
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    </table>
                </div>
            </div>

            <div class="col-md-3 tp-pic-box">پیک شما
                <span>{{ portion.amount }}</span>تـــومــــان
                <button name="pic-payment" id="pic-payment" onclick="picPayment01();">پرداخت</button>
            </div>

        </div>
    {% endfor %}
{% endblock %}

themeApp/templates/base.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="fa">
<head>
    <!-- Basic Page Metatags -->
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="description" content="سامانه پیک جهت سهولت در خریدهای گروهی و پرداخت های دسته جمعی ایجاد شده است و بهترین ابزار برای مدیریت هرچه بهتر خریدها در سفر و خابگاه میباشد" />
    <meta name="keywords" content="سامانه پیک,مدیریت مخارج گروهی,مدیریت مخارج خابگاه,مادر خرج,سایت مدیریت مخارج دسته جمعی" />
    <meta name="author" content="تیم توسعه تمنا" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"> <!-- Respomsive Design -->
    <!-- End Basic Page Metatags -->


    <!-- Import CSS Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}" type="text/css" media="screen"> <!-- Used for Respomsive Design -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}" media="screen">	<!-- Main Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css'%}" media="screen"> <!-- Font Icons -->
    <!-- End Import CSS Files -->

</head>
<body>

<!-- Whole Page Section -->
<div id="container" class="container">


    <!-- Header -->
    <div class="pagetitle">
        <div class="col-md-6">
            <a href="index.html"><img src="{% static 'images/header.png' %}" alt="لوگوی وب سایت پیک"></a>
        </div>
        <div class="col-md-6">
            <div class="tp-balance">
                موجودی حساب شما
                <span id="account-balance">{% block balance %}{% endblock %}</span>
            </div>
        </div>
    </div>
    <!-- End Header -->


    <!-- Main Section -->
    <div id="content" class="box-section">
        <!-- Define a Row -->
        <div class="row">
            <!-- Menu -->
            <div class="col-md-3">
                <div class="tp-menu">
                    <ul>
                        <li><a href="{% url 'purchaseApp.list_un_payed' %}"><i class="fa fa-shopping-cart"></i>خرید ها</a></li>
                        <li><a href="{% url 'purchaseApp.add.form' %}"><i class="fa fa-cart-plus"></i>اضافه کردن خرید</a></li>
                        <li><a href="{% url 'purchaseApp.list_payed' %}"><i class="fa fa-history"></i>تاریخچه خرید</a></li>
                        <li><a href="/group/all"><i class="fa fa-users"></i>گروه ها</a></li>
                        <li><a href="/group/new"><i class="fa fa-plus-square"></i>ساخت گروه</a></li>
                        <li><a href="/users/profile"><i class="fa fa-user"></i>پروفایل</a></li>
                        <li><a href="/accounting"><i class="fa fa-money"></i>مدیریت مالی</a></li>
                        <li><a href="/users/logout"><i class="fa fa-money"></i>خروج از حساب</a></li>
                    </ul>
                </div>
            </div>
            <!-- End Menu -->



            <!-- Profile Main Area -->
            <div class="col-md-9">
                <h2>{% block page_header %}{% endblock %}</h2>

                {% block content %}{% endblock %}

            </div>
            <!-- End Profile Main Area -->


        </div>
        <!-- End Define a Row -->


        <!-- Footer -->
        <div class="tp-footer">
            <p>
                2016 &copy; کلیه حقوق مادی و معنوی این وب سایت برای تیم توسعه تمنا محفوظ است .
            </p>
        </div>
        <!-- End Footer -->

    </div>
    <!-- End Main Section -->

</div>
<!-- End Whole Page Section -->


<!-- Import JS Files -->
<script type="text/javascript" src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<!-- Import JS Files -->


</body>
</html>